apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-runner
  labels:
    app: github-runner
spec:
  replicas: 4
  selector:
    matchLabels:
      app: github-runner
  template:
    metadata:
      labels:
        app: github-runner
    spec:
      containers:
      - name: docker
        image: docker:19.03.12-dind
        securityContext:
          privileged: true
        volumeMounts:
          - name: docker-certs
            mountPath: /certs
          - name: github-workdir
            mountPath: /home/github/_work

      - name: github-runner
        image: ercpereda/github-runner:1.0.0
        env:
        - name: DOCKER_HOST
          value: tcp://localhost:2376
        - name: DOCKER_TLS_VERIFY
          value: "1"
        - name: DOCKER_TLS_CERTDIR
          value: /certs
        - name: DOCKER_CERT_PATH
          value: /certs/client
        - name: GITHUB_OWNER
          value: ercpereda
        - name: GITHUB_REPOSITORY
          value: helm-charts
        - name: GITHUB_PAT
          valueFrom:
            secretKeyRef:
              name: pat-secret
              key: pat
        volumeMounts:
        - name: docker-certs
          mountPath: /certs
        - name: github-workdir
          mountPath: /home/github/_work

      volumes:
      - name: docker-certs
        emptyDir: {}
      - name: github-workdir
        emptyDir: {}
